---
title: 3D-Printed Astro Pi Flight Case
hero_image: images/banner.png
description: Use a 3D printer to create your very own Astro Pi flight case like the ones on the ISS
original_url: https://raspberrypi.org/learning/astro-pi-flight-case
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: rpi, physical computing, python
site_areas: ''
steps:
- title: Introduction
- title: What you will need
- title: Get the 3D files
- title: Print each part
- title: Remove the scaffolding
- title: Do a fit check
- title: Parts checklist
- title: Install the camera
- title: Install the Raspberry Pi
- title: Install stand offs for the Sense HAT
- title: Install the push-buttons
- title: Create the button wires
- title: Connect wires to the button terminals
- title: Connect the buttons to the Raspberry Pi
- title: Install the Sense HAT
- title: Assemble the case
- title: Test the buttons
- title: "Challenge: improve your case"
